[package]
name = "dicebot"
version = "0.1.0"
authors = ["Marc Chesebro <Marc.chesebro@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.7.0"
destiny = "0.2.1"
